# Site settings
title: Hi.
description: I am Michael. I am a Software Engineer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://michi.codes" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Weilb√§cher
user_description: I am Michael. I am a Software Engineer.
user_title: Lead Software Engineer/Architect
email: contact@michi.codes
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
